import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import IconNext from "../public/icon-next.svg";
import IconPrevious from "../public/icon-previous.svg";

export default function Home() {
  const name = "Fall Limited Edition Sneakers";
  const price = 125.0;
  const [items, setItems] = useState([
    {
      name: name,
      price: price,
      value: 1,
    },
    {
      name: name,
      price: price,
      value: 2,
    },
  ]);

  const productImages = [
    "/image-product-1.jpg",
    "/image-product-2.jpg",
    "/image-product-3.jpg",
    "/image-product-4.jpg",
  ];

  const addItem = () => {
    if (!value) {
      alert("Value cannot be blank!");
      return;
    }


    const addedItem = [
      ...items,
      {
        name,
        price,
        value: value,
      },
    ];

    setItems(addedItem);
    setValue(0);
  };

  const handleDelete = (index) => {
    const newItems = [...items];

    newItems.splice(index, 1);

    setItems(newItems);
  };

  const [value, setValue] = useState(0);

  const [showImage, setShowImage] = useState(productImages[0]);

  const [lightBoxDisplay, setLightBoxDisplay] = useState(false);
  const [cartDisplay, setCartDisplay] = useState(true);

  const handleMin = () => {
    setValue(value - 1);
  };

  const handlePlus = () => {
    setValue(value + 1);
  };

  const showNext = () => {
    let currentIndex = productImages.indexOf(showImage);
    console.log(currentIndex);
    let nextImage;
    currentIndex >= productImages.length - 1
      ? (nextImage = productImages[0])
      : (nextImage = productImages[currentIndex + 1]);
    setShowImage(nextImage);
  };

  const showPrev = () => {
    let currentIndex = productImages.indexOf(showImage);
    currentIndex == 0 ? (currentIndex = 4) : "";
    console.log(currentIndex);
    let prevImage = productImages[currentIndex - 1];
    setShowImage(prevImage);
  };

  const totalValue = items
    .map((item) => item.value)
    .reduce((prev, curr) => prev + curr, 0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Sneakers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <nav className={styles.nav}>
        <div className={styles.navLeft}>
          <img className={styles.navLogo} src="/logo.svg" alt="Logo" />
          <ul>
            <li>Collections</li>
            <li>Men</li>
            <li>Women</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
        </div>
        <div className={styles.navRight}>
          <div className={styles.cartContainer}>
            {items.length > 0 ? (
              <div className={styles.cartCount}>
                <p>{totalValue}</p>
              </div>
            ) : null}

            <img
              className={styles.cart}
              src="/icon-cart.svg"
              alt="Cart icon"
              onClick={() => setCartDisplay(!cartDisplay)}
            />
          </div>

          <img
            className={styles.navAvatar}
            src="/image-avatar.png"
            alt="Avatar"
          />
        </div>
      </nav>
      {/* Cart */}
      {cartDisplay ? (
        <div className={styles.cartBox}>
          <h4>Cart</h4>
          <hr />
          {/* Item */}
          {items.length > 0 ? (
            items.map((item, index) => (
              <div key={index} className={styles.cartWrapper}>
                <div className={styles.cartLeft}>
                  <img src={productImages[0]} alt="Product image" />
                </div>
                <div className={styles.cartCenter}>
                  <p>{item.name}</p>
                  <p>
                    ${item.price}.00 x {item.value}{" "}
                    <span className={styles.cartTotal}>
                      ${item.price * item.value}
                    </span>
                  </p>
                </div>
                <div className={styles.cartRight}>
                  <img
                    onClick={handleDelete}
                    src="/icon-delete.svg"
                    alt="delete"
                  />
                </div>
              </div>
            ))
          ) : (
            <div className={styles.emptyCart}>
              <p>Your cart is empty.</p>
            </div>
          )}
          {items.length > 0 ? (
            <button className={styles.checkoutButton}>Checkout</button>
          ) : null}
        </div>
      ) : (
        ""
      )}
      <main className={styles.main}>
        {/* Lightbox */}
        {lightBoxDisplay ? (
          <div className={styles.lightbox}>
            <div className={styles.lightboxCloseWrapper}>
              <button
                className={styles.lightboxClose}
                onClick={() => setLightBoxDisplay(false)}
              >
                <svg width="14" height="15" xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="m11.596.782 2.122 2.122L9.12 7.499l4.597 4.597-2.122 2.122L7 9.62l-4.595 4.597-2.122-2.122L4.878 7.5.282 2.904 2.404.782l4.595 4.596L11.596.782Z"
                    fill="#69707D"
                    fillRule="evenodd"
                  />
                </svg>
              </button>
            </div>
            <div className={styles.lightboxImage}>
              <button className={styles.lightboxButton} onClick={showPrev}>
                <svg width="12" height="18" xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M11 1 3 9l8 8"
                    stroke="#1D2026"
                    strokeWidth="3"
                    fill="none"
                    fillRule="evenodd"
                  />
                </svg>
              </button>
              <img src={showImage} alt="Product" />
              <button className={styles.lightboxButton} onClick={showNext}>
                <svg width="13" height="18" xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="m2 1 8 8-8 8"
                    stroke="#1D2026"
                    strokeWidth="3"
                    fill="none"
                    fillRule="evenodd"
                  />
                </svg>
              </button>
            </div>
            <div className={styles.lightboxThumb}>
              {productImages.map((product, id) => (
                <img
                  className={styles.imgThumb}
                  key={id}
                  src={product}
                  alt="Thumbnail"
                  onClick={() => {
                    setShowImage(product);
                    console.log(id);
                  }}
                />
              ))}
            </div>
          </div>
        ) : (
          ""
        )}

        <div className={styles.mainLeft}>
          <img src={productImages[1]} alt="Product" />
          <div className={styles.carousel}>
            {productImages.map((product) => (
              <img
                src={product}
                alt="Thumbnail"
                onClick={() => {
                  setLightBoxDisplay(true);
                  setShowImage(product);
                }}
              />
            ))}
          </div>
        </div>

        <div className={styles.mainRight}>
          <p className={styles.title}>SNEAKER COMPANY</p>
          <h1 className={styles.edition}>{name}</h1>
          <p className={styles.desc}>
            These low-profile sneakers are your perfect casual wear companion.
            Featuring a durable rubber outer sole, they'll withstand everything
            the weather can offer.
          </p>
          <div className={styles.mainRightDisc}>
            <h2>${price}</h2>
            <p>50%</p>
          </div>
          <p className={styles.cutOff}>$250.00</p>
          <div className={styles.buttonWrapper}>
            <button className={styles.buttonMin} onClick={handleMin}>
              <img src="/icon-minus.svg" alt="Minus" />
            </button>
            <input type="number" value={value} />
            <button className={styles.buttonPlus} onClick={handlePlus}>
              <img src="/icon-plus.svg" alt="Plus" />
            </button>
            <button onClick={addItem} className={styles.button}>
              <svg width="22" height="20" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M20.925 3.641H3.863L3.61.816A.896.896 0 0 0 2.717 0H.897a.896.896 0 1 0 0 1.792h1l1.031 11.483c.073.828.52 1.726 1.291 2.336C2.83 17.385 4.099 20 6.359 20c1.875 0 3.197-1.87 2.554-3.642h4.905c-.642 1.77.677 3.642 2.555 3.642a2.72 2.72 0 0 0 2.717-2.717 2.72 2.72 0 0 0-2.717-2.717H6.365c-.681 0-1.274-.41-1.53-1.009l14.321-.842a.896.896 0 0 0 .817-.677l1.821-7.283a.897.897 0 0 0-.87-1.114ZM6.358 18.208a.926.926 0 0 1 0-1.85.926.926 0 0 1 0 1.85Zm10.015 0a.926.926 0 0 1 0-1.85.926.926 0 0 1 0 1.85Zm2.021-7.243-13.8.81-.57-6.341h15.753l-1.383 5.53Z"
                  fill="#69707D"
                  fillRule="nonzero"
                />
              </svg>{" "}
              Add to cart
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
